namespace CryptoCloudApi.Models.Entities;

/// <summary>
/// Database entity for CryptoCloud payment invoices
/// </summary>
public class PaymentInvoice
{
    public long Id { get; set; }

    /// <summary>
    /// CryptoCloud invoice UUID (e.g., INV-XXXXXXXX)
    /// </summary>
    public string InvoiceUuid { get; set; } = string.Empty;

    /// <summary>
    /// Your internal order identifier
    /// </summary>
    public string OrderId { get; set; } = string.Empty;

    /// <summary>
    /// Invoice amount in fiat currency
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Invoice amount in USD
    /// </summary>
    public decimal AmountUsd { get; set; }

    /// <summary>
    /// Amount actually received
    /// </summary>
    public decimal? ReceivedAmount { get; set; }

    /// <summary>
    /// Fiat currency code (USD, EUR, etc.)
    /// </summary>
    public string Currency { get; set; } = "USD";

    /// <summary>
    /// Cryptocurrency code (BTC, ETH, USDT_TRC20, etc.)
    /// </summary>
    public string? CryptoCurrency { get; set; }

    /// <summary>
    /// Payment address generated by CryptoCloud
    /// </summary>
    public string? PaymentAddress { get; set; }

    /// <summary>
    /// Payment link for customer
    /// </summary>
    public string PaymentLink { get; set; } = string.Empty;

    /// <summary>
    /// Invoice status: created, paid, partial, overpaid, canceled, expired
    /// </summary>
    public string Status { get; set; } = "created";

    /// <summary>
    /// Customer email (optional)
    /// </summary>
    public string? CustomerEmail { get; set; }

    /// <summary>
    /// When the invoice was created
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the invoice expires
    /// </summary>
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// When the payment was completed
    /// </summary>
    public DateTime? PaidAt { get; set; }

    /// <summary>
    /// Last time we checked the status
    /// </summary>
    public DateTime? LastStatusCheck { get; set; }

    /// <summary>
    /// Transaction fees
    /// </summary>
    public decimal Fee { get; set; }

    /// <summary>
    /// Service commission
    /// </summary>
    public decimal ServiceFee { get; set; }

    /// <summary>
    /// Who pays the commission: client or merchant
    /// </summary>
    public string SideCommission { get; set; } = "client";

    /// <summary>
    /// Test mode flag
    /// </summary>
    public bool TestMode { get; set; }

    /// <summary>
    /// Additional metadata as JSON
    /// </summary>
    public string? Metadata { get; set; }

    /// <summary>
    /// Last update timestamp
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// List of transaction hashes
    /// </summary>
    public virtual ICollection<PaymentTransaction> Transactions { get; set; } = new List<PaymentTransaction>();
}
